version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  ui:
    build:
      context: /root/spti-health-mvc/
      dockerfile: Dockerfile
    container_name: my-ui
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - api
    restart: always

  api:
    build:
      context: /root/spti-health-api/
      dockerfile: Dockerfile
    container_name: my-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://65.1.25.204:3306/hospital?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8081:8080"
    networks:
      - my-network
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: hospital
    ports:
      - "3306:3306"
    networks:
      - my-network
